### ISSUE TITLE
Null Pointer Exception on Init

### ISSUE THREAD

**Issue by TheBitEffect** [RedAlertFTC/utils#1]
Currently, VuMarkForia throws a `NullPointerException`

Logcat Error Report:
```
Event loop threw an exception
java.lang.NullPointerException: Attempt to invoke interface method 'void org.firstinspires.ftc.robotcore.external.navigation.VuforiaTrackables.activate()' on a null object reference
    at org.firstinspires.ftc.teamcode.utils.VuMarkForia.init(VuMarkForia.java:60)
    at org.firstinspires.ftc.teamcode.PanicAutonomousBase.runOpMode(PanicAutonomousBase.java:54)
    at org.firstinspires.ftc.teamcode.PanicAutonomousRedOne.runOpMode(PanicAutonomousRedOne.java:15)
    at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper$1.run(LinearOpMode.java:305)
    at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:709)
    at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper.run(LinearOpMode.java:300)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:764)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by TheBitEffect** [comment]
No longer needed.
